CREATE TABLE issue_assets(
	id SERIAL PRIMARY KEY,
	publisher_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
	book_id INTEGER REFERENCES books(id) ON DELETE CASCADE,
	issue_id INTEGER REFERENCES issues(id) ON DELETE CASCADE,
	page_number SMALLINT DEFAULT 1 NOT NULL,
	photo_url VARCHAR NOT NULL,
	last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	date_created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);