CREATE TABLE genres(
	id SERIAL PRIMARY KEY,
	book_id INTEGER REFERENCES books(id) ON DELETE CASCADE,
	genre VARCHAR NOT NULL,
	date_created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(book_id, genre)
);